<h1>Oops</h1>
<p>Страница не найдена</p>
<? if( APPLICATION_ENV == "production" && isset(Boot::getInstance()->config->mail->error)): ?>
<?
  if( $e->getCode() != 404 ) {
    Boot_Mail::send(Boot::getInstance()->config->mail->error, "PNixx: Ошибка страницы",
      "<b>Error message:</b> " . $e->getMessage() . "<pre>" . $e->getTraceAsString() . "</pre>
      <pre>" . var_export($_COOKIE, true) . "
      				SERVER:
      				" . var_export($_SERVER, true) . "

      				SESSION:
      				" . var_export($_SESSION, true) . "

      				POST:
      				" . var_export($_POST, true) . "
      				</pre>"
    );
  }
?>
<? else: ?>
<b>Error message:</b> <?= $e->getMessage() ?>
<pre><?= $e->getTraceAsString() ?></pre>
<? endif ?>